{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "421672dc",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Name: Maxwell Tejera\n",
    "#Student number 109974513"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7d4d8c65",
   "metadata": {},
   "outputs": [],
   "source": [
    "#**************INTRODUCTION**************\n",
    "#I wanted to use the data from the Data ANalysis and Project Plan assignment - King County home sales for the May2014 - May2015 period.\n",
    "#Given I am somewhat familair with the data from personal experience,\n",
    "#I lived adjacent to King County during the time the data was recorded.\n",
    "#I also briefly worked for a consulting firm that analyzed the City of Seattle tax collections and the King County\n",
    "#Assessor data was important to that project. I think the dataset is large enough with lots of room for new, relevant variables\n",
    "#to be pulled from the base data."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "ecdfc1bc",
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "KaggleApi.authenticate() got an unexpected keyword argument 'api_key'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[5], line 11\u001b[0m\n\u001b[0;32m      8\u001b[0m api_key \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m0fcdf7130b385ce9dbe0333517c24448\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m      9\u001b[0m username \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mmaxwelltejera\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m---> 11\u001b[0m \u001b[43mkaggle\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mapi\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mauthenticate\u001b[49m\u001b[43m(\u001b[49m\u001b[43mapi_key\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mYOUR_API_KEY\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43musername\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mmaxwelltejera\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[0;32m     13\u001b[0m dataset_name \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mharlfoxem/housesalesprediction\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m     15\u001b[0m save_path \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mC:\u001b[39m\u001b[38;5;130;01m\\\\\u001b[39;00m\u001b[38;5;124mUsers\u001b[39m\u001b[38;5;130;01m\\\\\u001b[39;00m\u001b[38;5;124mtejer\u001b[39m\u001b[38;5;124m\"\u001b[39m\n",
      "\u001b[1;31mTypeError\u001b[0m: KaggleApi.authenticate() got an unexpected keyword argument 'api_key'"
     ]
    }
   ],
   "source": [
    "#The King County home sales data came in the form of comma separated values, CSV.\n",
    "#I want to use strictly Python commands to download the data and move it to an Atlas database.\n",
    "#Start by installing the Kaggle pip\n",
    "import subprocess #lets me install Kaggle from python code\n",
    "subprocess.run([\"pip\", \"install\", \"kaggle\"])\n",
    "import kaggle\n",
    "\n",
    "api_key = \"0fcdf7130b385ce9dbe0333517c24448\"\n",
    "username = \"maxwelltejera\"\n",
    "\n",
    "kaggle.api.authenticate(api_key=\"YOUR_API_KEY\", username=\"maxwelltejera\")\n",
    "\n",
    "dataset_name = \"harlfoxem/housesalesprediction\"\n",
    "\n",
    "save_path = \"C:\\\\Users\\\\tejer\"\n",
    "\n",
    "kaggle.api.dataset_download_files(dataset_name, path=save_path, unzip=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "826eef03",
   "metadata": {},
   "outputs": [
    {
     "ename": "FileNotFoundError",
     "evalue": "[Errno 2] No such file or directory: 'C:\\\\Users\\\\tejer\\\\kc_house_data.csv'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[4], line 17\u001b[0m\n\u001b[0;32m     14\u001b[0m \u001b[38;5;66;03m# Read the CSV file and convert it to a list of dictionaries\u001b[39;00m\n\u001b[0;32m     16\u001b[0m data \u001b[38;5;241m=\u001b[39m [] \u001b[38;5;66;03m#Starts data variable\u001b[39;00m\n\u001b[1;32m---> 17\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m \u001b[38;5;28;43mopen\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mcsv_file\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mr\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m \u001b[38;5;28;01mas\u001b[39;00m csv_file: \u001b[38;5;66;03m#Open CSV file\u001b[39;00m\n\u001b[0;32m     18\u001b[0m     csv_reader \u001b[38;5;241m=\u001b[39m csv\u001b[38;5;241m.\u001b[39mDictReader(csv_file) \u001b[38;5;66;03m#Starts reading as a dictionary\u001b[39;00m\n\u001b[0;32m     19\u001b[0m     \u001b[38;5;28;01mfor\u001b[39;00m row \u001b[38;5;129;01min\u001b[39;00m csv_reader: \u001b[38;5;66;03m#Adds an entry for each row of the CSV \u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\IPython\\core\\interactiveshell.py:282\u001b[0m, in \u001b[0;36m_modified_open\u001b[1;34m(file, *args, **kwargs)\u001b[0m\n\u001b[0;32m    275\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m file \u001b[38;5;129;01min\u001b[39;00m {\u001b[38;5;241m0\u001b[39m, \u001b[38;5;241m1\u001b[39m, \u001b[38;5;241m2\u001b[39m}:\n\u001b[0;32m    276\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\n\u001b[0;32m    277\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mIPython won\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mt let you open fd=\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mfile\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m by default \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    278\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mas it is likely to crash IPython. If you know what you are doing, \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    279\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124myou can use builtins\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m open.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m    280\u001b[0m     )\n\u001b[1;32m--> 282\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m io_open(file, \u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n",
      "\u001b[1;31mFileNotFoundError\u001b[0m: [Errno 2] No such file or directory: 'C:\\\\Users\\\\tejer\\\\kc_house_data.csv'"
     ]
    }
   ],
   "source": [
    "import csv\n",
    "import json\n",
    "\n",
    "#Import functionality for CSV and JSON files\n",
    "#Identify where CSV is located and where JSON will be written\n",
    "\n",
    "#Set location for where CSV file was downloaded\n",
    "#Set location for JSON file to be written. Given that it's being written by Python, this is a security concern.\n",
    "#Therefore write to the directory.\n",
    "\n",
    "csv_file = \"C:\\\\Users\\\\tejer\\\\kc_house_data.csv\"\n",
    "json_file = 'C:\\\\Users\\\\tejer\\\\kingcountysales.json'\n",
    "\n",
    "# Read the CSV file and convert it to a list of dictionaries\n",
    "\n",
    "data = [] #Starts data variable\n",
    "with open(csv_file, 'r') as csv_file: #Open CSV file\n",
    "    csv_reader = csv.DictReader(csv_file) #Starts reading as a dictionary\n",
    "    for row in csv_reader: #Adds an entry for each row of the CSV \n",
    "        data.append(row)\n",
    "\n",
    "# Write the data as JSON\n",
    "with open(json_file, 'w') as json_file:\n",
    "    json.dump(data, json_file, indent=4)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "804ec72d",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Checking my directory, the JSON file is there. Great! We've downloaded the data all through Python."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "d22055f9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pymongo in c:\\users\\tejer\\anaconda3\\lib\\site-packages (4.5.0)\n",
      "Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in c:\\users\\tejer\\anaconda3\\lib\\site-packages (from pymongo) (2.4.2)\n",
      "Pinged your deployment. You successfully connected to MongoDB!\n"
     ]
    }
   ],
   "source": [
    "#Establish MongoDB / Atlas Connection\n",
    "!pip install pymongo\n",
    "import pymongo #Get Mongo module going\n",
    "from pymongo import MongoClient #And MongoClient\n",
    "uri = \"mongodb+srv://tejeramaxwell:Darkhum0ur!@cluster0.36fc0wp.mongodb.net/?retryWrites=true&w=majority\" #Establish URI to my Atlas\n",
    "mc = pymongo.MongoClient(uri)\n",
    "client = MongoClient(uri)\n",
    "# Send a ping to confirm a successful connection\n",
    "try: #Test the Mongo connection\n",
    "    client.admin.command('ping')\n",
    "    print(\"Pinged your deployment. You successfully connected to MongoDB!\")\n",
    "except Exception as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "00feb92e",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Looks like we're talking to Atlas. Let's convert the JSON file to TXT.\n",
    "import json #Will need JSON module to \n",
    "with open(r\"C:\\Users\\tejer\\kingcountysales.json\", \"r\") as file:\n",
    "    kc_json = json.load(file) #Create a dictionary variable for the JSON string\n",
    "\n",
    "txt_file_path = r\"C:\\Users\\tejer\\kc_json.txt\"\n",
    "\n",
    "json_string = json.dumps(kc_json, indent=4)\n",
    "\n",
    "# Write the JSON string to the .txt file\n",
    "with open(txt_file_path, \"w\") as txt_file:\n",
    "    txt_file.write(json_string)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "7767d9f1",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "4d476175",
   "metadata": {},
   "outputs": [],
   "source": [
    "uri = \"mongodb+srv://tejeramaxwell:Darkhum0ur!@cluster0.36fc0wp.mongodb.net/?retryWrites=true&w=majority\"\n",
    "db_name = \"kingcounty\"\n",
    "collection_name = \"homesales\"\n",
    "json_file_path = \"C:\\\\Users\\\\tejer\\\\kc_json.txt\"\n",
    "\n",
    "# Read the JSON array from the file as a string\n",
    "with open(json_file_path, \"r\") as json_file:\n",
    "    json_array_string = json_file.read()\n",
    "\n",
    "# Parse the JSON array string into a list of dictionaries\n",
    "json_data_list = json.loads(json_array_string)\n",
    "\n",
    "# Establish a connection to MongoDB Atlas\n",
    "client = pymongo.MongoClient(uri)\n",
    "db = client.get_database(db_name)\n",
    "collection = db.get_collection(collection_name)\n",
    "\n",
    "# Insert each JSON object from the list into the MongoDB collection\n",
    "for json_object in json_data_list:\n",
    "    # Insert the JSON object as a document in the collection\n",
    "    result = collection.insert_one(json_object)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "60e56163",
   "metadata": {},
   "outputs": [],
   "source": [
    "#That worked, though it took a while. I'm not going to run it again but I think the insert_one and the 20,000+\n",
    "#rows in the CSV file really slowed down the process."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "169c79e7",
   "metadata": {},
   "outputs": [
    {
     "ename": "InvalidOperation",
     "evalue": "Cannot use MongoClient after close",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mInvalidOperation\u001b[0m                          Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[14], line 10\u001b[0m\n\u001b[0;32m      7\u001b[0m client2 \u001b[38;5;241m=\u001b[39m MongoClient(uri)\n\u001b[0;32m      9\u001b[0m sale_count \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m0\u001b[39m\n\u001b[1;32m---> 10\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m sale \u001b[38;5;129;01min\u001b[39;00m db\u001b[38;5;241m.\u001b[39mhomesales\u001b[38;5;241m.\u001b[39mfind():\n\u001b[0;32m     11\u001b[0m     sale_count \u001b[38;5;241m=\u001b[39m sale_count \u001b[38;5;241m+\u001b[39m \u001b[38;5;241m1\u001b[39m\n\u001b[0;32m     13\u001b[0m \u001b[38;5;28mprint\u001b[39m(sale_count)\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\pymongo\\cursor.py:1262\u001b[0m, in \u001b[0;36mCursor.next\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m   1260\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__empty:\n\u001b[0;32m   1261\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mStopIteration\u001b[39;00m\n\u001b[1;32m-> 1262\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mlen\u001b[39m(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__data) \u001b[38;5;129;01mor\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_refresh\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m:\n\u001b[0;32m   1263\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__data\u001b[38;5;241m.\u001b[39mpopleft()\n\u001b[0;32m   1264\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\pymongo\\cursor.py:1179\u001b[0m, in \u001b[0;36mCursor._refresh\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m   1157\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m InvalidOperation(\n\u001b[0;32m   1158\u001b[0m             \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mPassing a \u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mhint\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m is required when using the min/max query\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m   1159\u001b[0m             \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m option to ensure the query utilizes the correct index\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m   1160\u001b[0m         )\n\u001b[0;32m   1161\u001b[0m     q \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_query_class(\n\u001b[0;32m   1162\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__query_flags,\n\u001b[0;32m   1163\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__collection\u001b[38;5;241m.\u001b[39mdatabase\u001b[38;5;241m.\u001b[39mname,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   1177\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__exhaust,\n\u001b[0;32m   1178\u001b[0m     )\n\u001b[1;32m-> 1179\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m__send_message\u001b[49m\u001b[43m(\u001b[49m\u001b[43mq\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   1180\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__id:  \u001b[38;5;66;03m# Get More\u001b[39;00m\n\u001b[0;32m   1181\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__limit:\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\pymongo\\cursor.py:1060\u001b[0m, in \u001b[0;36mCursor.__send_message\u001b[1;34m(self, operation)\u001b[0m\n\u001b[0;32m   1057\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m InvalidOperation(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mexhaust cursors do not support auto encryption\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m   1059\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m-> 1060\u001b[0m     response \u001b[38;5;241m=\u001b[39m \u001b[43mclient\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_run_operation\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m   1061\u001b[0m \u001b[43m        \u001b[49m\u001b[43moperation\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_unpack_response\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43maddress\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m__address\u001b[49m\n\u001b[0;32m   1062\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   1063\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m OperationFailure \u001b[38;5;28;01mas\u001b[39;00m exc:\n\u001b[0;32m   1064\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m exc\u001b[38;5;241m.\u001b[39mcode \u001b[38;5;129;01min\u001b[39;00m _CURSOR_CLOSED_ERRORS \u001b[38;5;129;01mor\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__exhaust:\n\u001b[0;32m   1065\u001b[0m         \u001b[38;5;66;03m# Don't send killCursors because the cursor is already closed.\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\pymongo\\_csot.py:108\u001b[0m, in \u001b[0;36mapply.<locals>.csot_wrapper\u001b[1;34m(self, *args, **kwargs)\u001b[0m\n\u001b[0;32m    106\u001b[0m         \u001b[38;5;28;01mwith\u001b[39;00m _TimeoutContext(timeout):\n\u001b[0;32m    107\u001b[0m             \u001b[38;5;28;01mreturn\u001b[39;00m func(\u001b[38;5;28mself\u001b[39m, \u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[1;32m--> 108\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m func(\u001b[38;5;28mself\u001b[39m, \u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\pymongo\\mongo_client.py:1388\u001b[0m, in \u001b[0;36mMongoClient._run_operation\u001b[1;34m(self, operation, unpack_res, address)\u001b[0m\n\u001b[0;32m   1383\u001b[0m     operation\u001b[38;5;241m.\u001b[39mreset()  \u001b[38;5;66;03m# Reset op in case of retry.\u001b[39;00m\n\u001b[0;32m   1384\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m server\u001b[38;5;241m.\u001b[39mrun_operation(\n\u001b[0;32m   1385\u001b[0m         conn, operation, read_preference, \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_event_listeners, unpack_res\n\u001b[0;32m   1386\u001b[0m     )\n\u001b[1;32m-> 1388\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_retryable_read\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m   1389\u001b[0m \u001b[43m    \u001b[49m\u001b[43m_cmd\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m   1390\u001b[0m \u001b[43m    \u001b[49m\u001b[43moperation\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mread_preference\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m   1391\u001b[0m \u001b[43m    \u001b[49m\u001b[43moperation\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msession\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m   1392\u001b[0m \u001b[43m    \u001b[49m\u001b[43maddress\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43maddress\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m   1393\u001b[0m \u001b[43m    \u001b[49m\u001b[43mretryable\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43misinstance\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43moperation\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmessage\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_Query\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m   1394\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\pymongo\\_csot.py:108\u001b[0m, in \u001b[0;36mapply.<locals>.csot_wrapper\u001b[1;34m(self, *args, **kwargs)\u001b[0m\n\u001b[0;32m    106\u001b[0m         \u001b[38;5;28;01mwith\u001b[39;00m _TimeoutContext(timeout):\n\u001b[0;32m    107\u001b[0m             \u001b[38;5;28;01mreturn\u001b[39;00m func(\u001b[38;5;28mself\u001b[39m, \u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[1;32m--> 108\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m func(\u001b[38;5;28mself\u001b[39m, \u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\pymongo\\mongo_client.py:1525\u001b[0m, in \u001b[0;36mMongoClient._retryable_read\u001b[1;34m(self, func, read_pref, session, address, retryable)\u001b[0m\n\u001b[0;32m   1523\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m last_error\n\u001b[0;32m   1524\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m-> 1525\u001b[0m     server \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_select_server\u001b[49m\u001b[43m(\u001b[49m\u001b[43mread_pref\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43msession\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43maddress\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43maddress\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   1526\u001b[0m     \u001b[38;5;28;01mwith\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_conn_from_server(read_pref, server, session) \u001b[38;5;28;01mas\u001b[39;00m (\n\u001b[0;32m   1527\u001b[0m         conn,\n\u001b[0;32m   1528\u001b[0m         read_pref,\n\u001b[0;32m   1529\u001b[0m     ):\n\u001b[0;32m   1530\u001b[0m         \u001b[38;5;28;01mif\u001b[39;00m retrying \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m retryable:\n\u001b[0;32m   1531\u001b[0m             \u001b[38;5;66;03m# A retry is not possible because this server does\u001b[39;00m\n\u001b[0;32m   1532\u001b[0m             \u001b[38;5;66;03m# not support retryable reads, raise the last error.\u001b[39;00m\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\pymongo\\mongo_client.py:1286\u001b[0m, in \u001b[0;36mMongoClient._select_server\u001b[1;34m(self, server_selector, session, address)\u001b[0m\n\u001b[0;32m   1275\u001b[0m \u001b[38;5;124;03m\"\"\"Select a server to run an operation on this client.\u001b[39;00m\n\u001b[0;32m   1276\u001b[0m \n\u001b[0;32m   1277\u001b[0m \u001b[38;5;124;03m:Parameters:\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   1283\u001b[0m \u001b[38;5;124;03m    to a specific server, used for getMore.\u001b[39;00m\n\u001b[0;32m   1284\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[0;32m   1285\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m-> 1286\u001b[0m     topology \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_get_topology\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   1287\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m session \u001b[38;5;129;01mand\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m session\u001b[38;5;241m.\u001b[39min_transaction:\n\u001b[0;32m   1288\u001b[0m         session\u001b[38;5;241m.\u001b[39m_transaction\u001b[38;5;241m.\u001b[39mreset()\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\pymongo\\mongo_client.py:1232\u001b[0m, in \u001b[0;36mMongoClient._get_topology\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m   1226\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_get_topology\u001b[39m(\u001b[38;5;28mself\u001b[39m) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m Topology:\n\u001b[0;32m   1227\u001b[0m     \u001b[38;5;124;03m\"\"\"Get the internal :class:`~pymongo.topology.Topology` object.\u001b[39;00m\n\u001b[0;32m   1228\u001b[0m \n\u001b[0;32m   1229\u001b[0m \u001b[38;5;124;03m    If this client was created with \"connect=False\", calling _get_topology\u001b[39;00m\n\u001b[0;32m   1230\u001b[0m \u001b[38;5;124;03m    launches the connection process in the background.\u001b[39;00m\n\u001b[0;32m   1231\u001b[0m \u001b[38;5;124;03m    \"\"\"\u001b[39;00m\n\u001b[1;32m-> 1232\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_topology\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mopen\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   1233\u001b[0m     \u001b[38;5;28;01mwith\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m__lock:\n\u001b[0;32m   1234\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_kill_cursors_executor\u001b[38;5;241m.\u001b[39mopen()\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\pymongo\\topology.py:211\u001b[0m, in \u001b[0;36mTopology.open\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    208\u001b[0m         \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_session_pool\u001b[38;5;241m.\u001b[39mreset()\n\u001b[0;32m    210\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_lock:\n\u001b[1;32m--> 211\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_ensure_opened\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32m~\\anaconda3\\lib\\site-packages\\pymongo\\topology.py:637\u001b[0m, in \u001b[0;36mTopology._ensure_opened\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    632\u001b[0m \u001b[38;5;124;03m\"\"\"Start monitors, or restart after a fork.\u001b[39;00m\n\u001b[0;32m    633\u001b[0m \n\u001b[0;32m    634\u001b[0m \u001b[38;5;124;03mHold the lock when calling this.\u001b[39;00m\n\u001b[0;32m    635\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[0;32m    636\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_closed:\n\u001b[1;32m--> 637\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m InvalidOperation(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mCannot use MongoClient after close\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m    639\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_opened:\n\u001b[0;32m    640\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_opened \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mTrue\u001b[39;00m\n",
      "\u001b[1;31mInvalidOperation\u001b[0m: Cannot use MongoClient after close"
     ]
    }
   ],
   "source": [
    "#Looking on the Atlas side, it seems like the data is showing up there. Let's do some analytics to test the data.\n",
    "#Let's start by counting the number of sales and verifying it's the same we saw in the CSV file.\n",
    "import pymongo #Get Mongo module going\n",
    "from pymongo import MongoClient #And MongoClient\n",
    "uri = \"mongodb+srv://tejeramaxwell:Darkhum0ur!@cluster0.36fc0wp.mongodb.net/?retryWrites=true&w=majority\"\n",
    "mc = pymongo.MongoClient(uri)\n",
    "client = MongoClient(uri)\n",
    "\n",
    "sale_count = 0\n",
    "for sale in db.homesales.find():\n",
    "    sale_count = sale_count + 1\n",
    "\n",
    "print(sale_count)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "35f457f0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "What is the number of bedrooms of the sale you want to search?\n",
      "7129300520\n",
      "[\n",
      "  {\n",
      "    \"date\": \"20141013T000000\",\n",
      "    \"price\": 221900,\n",
      "    \"bedrooms\": 3,\n",
      "    \"bathrooms\": 1,\n",
      "    \"sqft_living\": 1180,\n",
      "    \"sqft_lot\": 5650,\n",
      "    \"floors\": 1,\n",
      "    \"waterfront\": 0,\n",
      "    \"view\": 0,\n",
      "    \"condition\": 3,\n",
      "    \"grade\": 7,\n",
      "    \"sqft_above\": 1180,\n",
      "    \"sqft_basement\": 0,\n",
      "    \"yr_built\": 1955,\n",
      "    \"yr_renovated\": 0,\n",
      "    \"zipcode\": 98178,\n",
      "    \"lat\": 47.5112,\n",
      "    \"long\": -122.257,\n",
      "    \"sqft_living15\": 1340,\n",
      "    \"sqft_lot15\": 5650\n",
      "  }\n",
      "]\n"
     ]
    }
   ],
   "source": [
    "#Looks like it has right number of rows.\n",
    "#Let's print a single home sale and see if it shows all the variables we want it to.\n",
    "\n",
    "search_homesale_id = int(input('What is the number of bedrooms of the sale you want to search?\\n')) #prompt user for search term\n",
    "cursor = db.homesales.find( \n",
    "    { \"id\": search_homesale_id }, \n",
    "    { \"date\": 1, \"price\": 1, \"bedrooms\": 1, \"bathrooms\": 1, \"sqft_living\": 1,\"sqft_lot\": 1, \"floors\": 1, \"waterfront\": 1, \"view\": 1, \"condition\": 1, \"grade\": 1, \"sqft_above\": 1, \"sqft_basement\":1, \"yr_built\": 1, \"yr_renovated\": 1, \"zipcode\": 1, \"lat\": 1, \"long\": 1, \"sqft_living15\": 1, \"sqft_lot15\": 1, \"_id\": 0,} ) #All variables less _id \n",
    "from bson.json_util import dumps\n",
    "print(dumps(cursor, indent=2))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "de196e4e",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Great, looks like we can pull a document of a homesale using an integer ID. It contains all the variables I'd like."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "f6a461de",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Let's try to do the extra functionality part of the assignment. Looking at the dates for the homesales, I don't like how\n",
    "#the date is formatted. It seems the first eight characters are in the YYYYMMDD format.\n",
    "#We should be able to convert it and update all the documents in our database."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "38d7b0ee",
   "metadata": {},
   "outputs": [],
   "source": [
    "for sale in db.homesales.find({}): #iterate through the collection\n",
    "    old_date = sale[\"date\"] #establish original date to transform\n",
    "    new_date = old_date[:4] + '-' + old_date[4:6] + '-' + old_date[6:]  \n",
    "    # Extract the first 4 characters to of the original date format, add a hypen, then the following 2, add hyphen, then final 2\n",
    "    db.homesales.update_one( #update on each iteration\n",
    "        {\"_id\": sale[\"_id\"]},  # Match the document by its _id\n",
    "        {\"$set\": {\"date\": new_date}}  # Update the date field with the new format\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9c3943a7",
   "metadata": {},
   "outputs": [],
   "source": [
    "#I've reformatted the dates in the record. I want to revisit the CSV -> JSON conversion.\n",
    "#Let's see if I can download the file from Kaggle as JSON directly."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "id": "191cc939",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Start by installing the Kaggle pip\n",
    "import subprocess\n",
    "subprocess.run([\"pip\", \"install\", \"kaggle\"])\n",
    "import kaggle"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 59,
   "id": "2d92bf87",
   "metadata": {},
   "outputs": [],
   "source": [
    "dataset_name = \"andykrause/kingcountysales\"\n",
    "\n",
    "save_path = \"C:\\\\Users\\\\tejer\\\\OneDrive\\\\Desktop\\\\Intro to Python Course\\\\Networked Programs and Files MongoDB Assignment\"\n",
    "\n",
    "kaggle.api.dataset_download_files(dataset_name, path=save_path, unzip=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "id": "e57463ea",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3d1f26d5",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
